MONGO_URI=
NODE_ENV= development | production

AUTH0_DOMAIN=
AUTH0_AUTH_CLIENT_ID=
AUTH0_AUTH_CLIENT_SECRET=
AUTH0_AUTH_CONNECTION=

AUTH0_AUTH_MGMT_ID=
AUTH0_AUTH_MGMT_SECRET=
AUTH0_AUTH_MGMT_AUDIENCE=