export enum ExceptionCodes {
  ARGUMENT_INVALID = 'GENERIC.ARGUMENT_INVALID',
  ARGUMENT_OUT_OF_RANGE = 'GENERIC.ARGUMENT_OUT_OF_RANGE',
  ARGUMENT_NOT_PROVIDED = 'GENERIC.ARGUMENT_NOT_PROVIDED',
  NOT_FOUND = 'GENERIC.NOT_FOUND',
  CONFLICT = 'GENERIC.CONFLICT',
  INTERNAL_SERVER_ERROR = 'GENERIC.INTERNAL_SERVER_ERROR',
  UNAUTHORIZED = 'GENERIC.UNAUTHORIZED',
  FORBBIDEN = 'GENERIC.FORBBIDEN',
  SERVICE_UNAVAILABLE = 'GENERIC.SERVICE_UNAVAILABLE',
}
